### ISSUE TITLE
No matter what MODE is configured, RVTEST_RV64UV is generated in the assembly case

### ISSUE THREAD

**Issue by Shanchuang666** [chipsalliance/riscv-vector-tests#47]
After I successfully run the three machine/user/virtual MODE configurations, I find that RVTEST_RV64UV is configured in all the generated cases. Is there a problem here and what is the consideration.

![image](https://github.com/user-attachments/assets/e3225999-4515-4da7-855d-1a4699b103cb)

![image](https://github.com/user-attachments/assets/f1a6e43e-9ab7-4420-b1cc-9bbea703bd88)

**Comment by ksco** [comment]
There is no issue, we’re testing user mode instructions no matter what the mode is.
