### ISSUE TITLE
Query about the test generator

### ISSUE THREAD

**Issue by latifbhatti** [chipsalliance/riscv-vector-tests#48]
Hello, I want to verify my riscv vector extension co-processor, but couldn't find the vector test suites in the riscv-arch-test repo. I just found this generator for vector tests, so I wanted to know more about this test generator, does it generates compliance test suites? the one that dumps signatures?

**Comment by ksco** [comment]
No, there is no dumps signatures.

**Comment by ksco** [comment]
Closed for long periods of inactivity.
