### ISSUE TITLE
How to check resultdata

### ISSUE THREAD

**Issue by chenyuanyping** [chipsalliance/riscv-vector-tests#57]
Case: out/v128x32machine/tests/stage1/vaadd_vv-0.S
It seems that the final results were not checked and compared.
![vadd_vv](https://github.com/user-attachments/assets/08bec7c9-e9c5-44af-a5eb-0f08eca72be8)

**Comment by ksco** [comment]
The final assembly is in stage2, not stage1.

**Comment by chenyuanyping** [comment]
Thanks for the answer. I also want to know the function of the .word command.
And When I generated stage2, the following error occurred
![stage2](https://github.com/user-attachments/assets/7adfa06c-599b-4ba9-a8cc-463dfc979f48)

**Comment by ksco** [comment]
Can you try XLEN=64 to see if it's working? Maybe something is wrong under XLEN=32?

**Comment by chenyuanyping** [comment]
I have tried and the error occurs as follows
![RISCV_ERROR](https://github.com/user-attachments/assets/35f3b1da-5eac-4a33-8fae-f185656dc78e)

**Comment by ksco** [comment]
Maybe something is wrong with your setup, check how we did this in the CI, refer to https://github.com/chipsalliance/riscv-vector-tests/blob/main/.github/workflows/build-and-test.yml.

**Comment by chenyuanyping** [comment]
Thanks,I will try

**Comment by ksco** [comment]
Oh, about the magic .word, check the "How it works" section in README. We modified spike to add a "magic" instruction which generates reference result checking code, and then merged back to the original assembly file.

**Comment by chenyuanyping** [comment]
thanks for modified.  I tried VLEN=128,XLEN=64 and it passed, but when I tried VLEN=128,XLEN=32, it gave the error as below
![image](https://github.com/user-attachments/assets/f551e5bf-822a-4ede-a34f-1709077d5587)

**Comment by chenyuanyping** [comment]
I run 
 `make generate-stage1 --environment-overrides VLEN=128 XLEN=32 ` 
`make all -j128 --environment-overrides VLEN=128 XLEN=32   `

**Comment by ksco** [comment]
It seems XLEN=32 was not well tested in some cases, I'll check later.

**Comment by chenyuanyping** [comment]
Thanks,I have another question, I want to change the memory address of `pspike`, but it didn’t seem to take effect at the time. Where should I change it?
![image](https://github.com/user-attachments/assets/10304682-a47a-4f1b-9386-080ef747de7d)
![image](https://github.com/user-attachments/assets/b27a4b0c-6ed4-41a6-8463-0daa3bc1d5d7)

**Comment by chenyuanyping** [comment]
normal spike can do  `spike -m0x0:0x400000`,But pspike doesn’t seem to work

**Comment by ksco** [comment]
https://github.com/chipsalliance/riscv-vector-tests/commit/5bd2b3d7a43aa129d6d3e7f24bacf1f576ecbe3a should fix the XLEN=32 issue, please open a new ticket for other issues if any.

**Comment by chenyuanyping** [comment]
Thank you for fixing the issue!
